---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: trigger installation handler execution
  meta: flush_handlers
- name: templatize dnsmasq configuration...
  become: yes
  become_user: root
  notify: dnsmasq_configure_restart
  template:
    src: dnsmasq.conf.j2
    dest: '{{ dnsmasq_configure_conf_dir | default("/etc") }}/{{ dnsmasq_configure_conf_filename | default("dnsmasq.conf") }}'
    mode: '{{ item.m | default("0644") }}'
- name: activate dnsmasq service
  become: yes
  become_user: root
  when: dnsmasq_activate | default(True)
  service:
    name: dnsmasq
    state: started
    enabled: yes
    
