---
- name: templatize DNS redirects...
  become: yes
  become_user: root
  when: dnsmasq_domain_redirects is defined
  template:
    src: dns_domain_redirect.j2
    dest: '{{dnsmasq_dropins_dir}}/{{dnsmasq_domain_redirects_prefix|default("")}}dns-domain-redirects'