---
- name: templatize dnsmasq configuration...
  become: yes
  become_user: root
  template:
    src: dnsmasq.conf.j2
    dest: '{{ dnsmasq_configure_conf_dir | default("/etc") }}/{{ dnsmasq_configure_conf_filename | default("dnsmasq.conf") }}'
    mode: '{{ item.m | default("0644") }}'
- name: activate dnsmasq service
  become: yes
  become_user: root
  when: dnsmasq_activate | bool | default(True)
  service:
    name: dnsmasq
    state: started
    enabled: yes
    
