---
- name: templatize configuration...
  become: yes
  become_user: root
  with_items:
    - f: dnsmasq.conf
      d: /etc
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
