---
# handlers file for dnsmasq-configure
- name: disable_systemd_resolved
  become: '{{ dnsmasq_privilege_escalate }}'
  become_user: root
  when: dnsmasq_disable_systemd_resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
- name: dnsmasq_configure_restart
  become: yes
  become_user: root
  when: dnsmasq_activate | default(True)
  service:
    name: dnsmasq
    state: restarted
